#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Credit")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertMaster_Credit(Master_Credit instance);
  partial void UpdateMaster_Credit(Master_Credit instance);
  partial void DeleteMaster_Credit(Master_Credit instance);
  partial void InsertMaster_Credit_Grid3(Master_Credit_Grid3 instance);
  partial void UpdateMaster_Credit_Grid3(Master_Credit_Grid3 instance);
  partial void DeleteMaster_Credit_Grid3(Master_Credit_Grid3 instance);
  partial void InsertMaster_Credit_Grid1(Master_Credit_Grid1 instance);
  partial void UpdateMaster_Credit_Grid1(Master_Credit_Grid1 instance);
  partial void DeleteMaster_Credit_Grid1(Master_Credit_Grid1 instance);
  partial void InsertMaster_Credit_Grid2(Master_Credit_Grid2 instance);
  partial void UpdateMaster_Credit_Grid2(Master_Credit_Grid2 instance);
  partial void DeleteMaster_Credit_Grid2(Master_Credit_Grid2 instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CreditConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Master_Credit> Master_Credits
	{
		get
		{
			return this.GetTable<Master_Credit>();
		}
	}
	
	public System.Data.Linq.Table<Master_Credit_Grid3> Master_Credit_Grid3s
	{
		get
		{
			return this.GetTable<Master_Credit_Grid3>();
		}
	}
	
	public System.Data.Linq.Table<Master_Credit_Grid1> Master_Credit_Grid1s
	{
		get
		{
			return this.GetTable<Master_Credit_Grid1>();
		}
	}
	
	public System.Data.Linq.Table<Master_Credit_Grid2> Master_Credit_Grid2s
	{
		get
		{
			return this.GetTable<Master_Credit_Grid2>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Master_Credit")]
public partial class Master_Credit : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _CustomerName;
	
	private string _BelegunNumber;
	
	private string _KundenNumber;
	
	private System.Nullable<System.DateTime> _LieferDatum;
	
	private System.Nullable<System.DateTime> _Rechnungsdatum;
	
	private string _Varkaufer;
	
	private string _IhreUID;
	
	private string _Address;
	
	private bool _LockStatus;
	
	private string _Comment;
	
	private EntitySet<Master_Credit_Grid3> _Master_Credit_Grid3s;
	
	private EntitySet<Master_Credit_Grid1> _Master_Credit_Grid1s;
	
	private EntitySet<Master_Credit_Grid2> _Master_Credit_Grid2s;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCustomerNameChanging(string value);
    partial void OnCustomerNameChanged();
    partial void OnBelegunNumberChanging(string value);
    partial void OnBelegunNumberChanged();
    partial void OnKundenNumberChanging(string value);
    partial void OnKundenNumberChanged();
    partial void OnLieferDatumChanging(System.Nullable<System.DateTime> value);
    partial void OnLieferDatumChanged();
    partial void OnRechnungsdatumChanging(System.Nullable<System.DateTime> value);
    partial void OnRechnungsdatumChanged();
    partial void OnVarkauferChanging(string value);
    partial void OnVarkauferChanged();
    partial void OnIhreUIDChanging(string value);
    partial void OnIhreUIDChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnLockStatusChanging(bool value);
    partial void OnLockStatusChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
	
	public Master_Credit()
	{
		this._Master_Credit_Grid3s = new EntitySet<Master_Credit_Grid3>(new Action<Master_Credit_Grid3>(this.attach_Master_Credit_Grid3s), new Action<Master_Credit_Grid3>(this.detach_Master_Credit_Grid3s));
		this._Master_Credit_Grid1s = new EntitySet<Master_Credit_Grid1>(new Action<Master_Credit_Grid1>(this.attach_Master_Credit_Grid1s), new Action<Master_Credit_Grid1>(this.detach_Master_Credit_Grid1s));
		this._Master_Credit_Grid2s = new EntitySet<Master_Credit_Grid2>(new Action<Master_Credit_Grid2>(this.attach_Master_Credit_Grid2s), new Action<Master_Credit_Grid2>(this.detach_Master_Credit_Grid2s));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="VarChar(50)")]
	public string CustomerName
	{
		get
		{
			return this._CustomerName;
		}
		set
		{
			if ((this._CustomerName != value))
			{
				this.OnCustomerNameChanging(value);
				this.SendPropertyChanging();
				this._CustomerName = value;
				this.SendPropertyChanged("CustomerName");
				this.OnCustomerNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BelegunNumber", DbType="VarChar(50)")]
	public string BelegunNumber
	{
		get
		{
			return this._BelegunNumber;
		}
		set
		{
			if ((this._BelegunNumber != value))
			{
				this.OnBelegunNumberChanging(value);
				this.SendPropertyChanging();
				this._BelegunNumber = value;
				this.SendPropertyChanged("BelegunNumber");
				this.OnBelegunNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KundenNumber", DbType="VarChar(50)")]
	public string KundenNumber
	{
		get
		{
			return this._KundenNumber;
		}
		set
		{
			if ((this._KundenNumber != value))
			{
				this.OnKundenNumberChanging(value);
				this.SendPropertyChanging();
				this._KundenNumber = value;
				this.SendPropertyChanged("KundenNumber");
				this.OnKundenNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LieferDatum", DbType="DateTime")]
	public System.Nullable<System.DateTime> LieferDatum
	{
		get
		{
			return this._LieferDatum;
		}
		set
		{
			if ((this._LieferDatum != value))
			{
				this.OnLieferDatumChanging(value);
				this.SendPropertyChanging();
				this._LieferDatum = value;
				this.SendPropertyChanged("LieferDatum");
				this.OnLieferDatumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rechnungsdatum", DbType="DateTime")]
	public System.Nullable<System.DateTime> Rechnungsdatum
	{
		get
		{
			return this._Rechnungsdatum;
		}
		set
		{
			if ((this._Rechnungsdatum != value))
			{
				this.OnRechnungsdatumChanging(value);
				this.SendPropertyChanging();
				this._Rechnungsdatum = value;
				this.SendPropertyChanged("Rechnungsdatum");
				this.OnRechnungsdatumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Varkaufer", DbType="VarChar(50)")]
	public string Varkaufer
	{
		get
		{
			return this._Varkaufer;
		}
		set
		{
			if ((this._Varkaufer != value))
			{
				this.OnVarkauferChanging(value);
				this.SendPropertyChanging();
				this._Varkaufer = value;
				this.SendPropertyChanged("Varkaufer");
				this.OnVarkauferChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IhreUID", DbType="VarChar(50)")]
	public string IhreUID
	{
		get
		{
			return this._IhreUID;
		}
		set
		{
			if ((this._IhreUID != value))
			{
				this.OnIhreUIDChanging(value);
				this.SendPropertyChanging();
				this._IhreUID = value;
				this.SendPropertyChanged("IhreUID");
				this.OnIhreUIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(500)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LockStatus")]
	public bool LockStatus
	{
		get
		{
			return this._LockStatus;
		}
		set
		{
			if ((this._LockStatus != value))
			{
				this.OnLockStatusChanging(value);
				this.SendPropertyChanging();
				this._LockStatus = value;
				this.SendPropertyChanged("LockStatus");
				this.OnLockStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", CanBeNull=false)]
	public string Comment
	{
		get
		{
			return this._Comment;
		}
		set
		{
			if ((this._Comment != value))
			{
				this.OnCommentChanging(value);
				this.SendPropertyChanging();
				this._Comment = value;
				this.SendPropertyChanged("Comment");
				this.OnCommentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Master_Credit_Master_Credit_Grid3", Storage="_Master_Credit_Grid3s", ThisKey="Id", OtherKey="MasterId")]
	public EntitySet<Master_Credit_Grid3> Master_Credit_Grid3s
	{
		get
		{
			return this._Master_Credit_Grid3s;
		}
		set
		{
			this._Master_Credit_Grid3s.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Master_Credit_Master_Credit_Grid1", Storage="_Master_Credit_Grid1s", ThisKey="Id", OtherKey="MasterId")]
	public EntitySet<Master_Credit_Grid1> Master_Credit_Grid1s
	{
		get
		{
			return this._Master_Credit_Grid1s;
		}
		set
		{
			this._Master_Credit_Grid1s.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Master_Credit_Master_Credit_Grid2", Storage="_Master_Credit_Grid2s", ThisKey="Id", OtherKey="MasterId")]
	public EntitySet<Master_Credit_Grid2> Master_Credit_Grid2s
	{
		get
		{
			return this._Master_Credit_Grid2s;
		}
		set
		{
			this._Master_Credit_Grid2s.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Master_Credit_Grid3s(Master_Credit_Grid3 entity)
	{
		this.SendPropertyChanging();
		entity.Master_Credit = this;
	}
	
	private void detach_Master_Credit_Grid3s(Master_Credit_Grid3 entity)
	{
		this.SendPropertyChanging();
		entity.Master_Credit = null;
	}
	
	private void attach_Master_Credit_Grid1s(Master_Credit_Grid1 entity)
	{
		this.SendPropertyChanging();
		entity.Master_Credit = this;
	}
	
	private void detach_Master_Credit_Grid1s(Master_Credit_Grid1 entity)
	{
		this.SendPropertyChanging();
		entity.Master_Credit = null;
	}
	
	private void attach_Master_Credit_Grid2s(Master_Credit_Grid2 entity)
	{
		this.SendPropertyChanging();
		entity.Master_Credit = this;
	}
	
	private void detach_Master_Credit_Grid2s(Master_Credit_Grid2 entity)
	{
		this.SendPropertyChanging();
		entity.Master_Credit = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Master_Credit_Grid3")]
public partial class Master_Credit_Grid3 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Beschreibung;
	
	private System.Nullable<int> _Lange;
	
	private string _Züchter;
	
	private string _VP;
	
	private System.Nullable<int> _Menge;
	
	private System.Nullable<int> _Einheit;
	
	private System.Nullable<decimal> _Preis;
	
	private string _Steuer;
	
	private System.Nullable<decimal> _Betrag;
	
	private System.Nullable<int> _MasterId;
	
	private EntityRef<Master_Credit> _Master_Credit;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBeschreibungChanging(string value);
    partial void OnBeschreibungChanged();
    partial void OnLangeChanging(System.Nullable<int> value);
    partial void OnLangeChanged();
    partial void OnZüchterChanging(string value);
    partial void OnZüchterChanged();
    partial void OnVPChanging(string value);
    partial void OnVPChanged();
    partial void OnMengeChanging(System.Nullable<int> value);
    partial void OnMengeChanged();
    partial void OnEinheitChanging(System.Nullable<int> value);
    partial void OnEinheitChanged();
    partial void OnPreisChanging(System.Nullable<decimal> value);
    partial void OnPreisChanged();
    partial void OnSteuerChanging(string value);
    partial void OnSteuerChanged();
    partial void OnBetragChanging(System.Nullable<decimal> value);
    partial void OnBetragChanged();
    partial void OnMasterIdChanging(System.Nullable<int> value);
    partial void OnMasterIdChanged();
    #endregion
	
	public Master_Credit_Grid3()
	{
		this._Master_Credit = default(EntityRef<Master_Credit>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beschreibung", DbType="VarChar(50)")]
	public string Beschreibung
	{
		get
		{
			return this._Beschreibung;
		}
		set
		{
			if ((this._Beschreibung != value))
			{
				this.OnBeschreibungChanging(value);
				this.SendPropertyChanging();
				this._Beschreibung = value;
				this.SendPropertyChanged("Beschreibung");
				this.OnBeschreibungChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lange", DbType="Int")]
	public System.Nullable<int> Lange
	{
		get
		{
			return this._Lange;
		}
		set
		{
			if ((this._Lange != value))
			{
				this.OnLangeChanging(value);
				this.SendPropertyChanging();
				this._Lange = value;
				this.SendPropertyChanged("Lange");
				this.OnLangeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Züchter", DbType="VarChar(50)")]
	public string Züchter
	{
		get
		{
			return this._Züchter;
		}
		set
		{
			if ((this._Züchter != value))
			{
				this.OnZüchterChanging(value);
				this.SendPropertyChanging();
				this._Züchter = value;
				this.SendPropertyChanged("Züchter");
				this.OnZüchterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VP", DbType="VarChar(50)")]
	public string VP
	{
		get
		{
			return this._VP;
		}
		set
		{
			if ((this._VP != value))
			{
				this.OnVPChanging(value);
				this.SendPropertyChanging();
				this._VP = value;
				this.SendPropertyChanged("VP");
				this.OnVPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Menge", DbType="Int")]
	public System.Nullable<int> Menge
	{
		get
		{
			return this._Menge;
		}
		set
		{
			if ((this._Menge != value))
			{
				this.OnMengeChanging(value);
				this.SendPropertyChanging();
				this._Menge = value;
				this.SendPropertyChanged("Menge");
				this.OnMengeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Einheit", DbType="Int")]
	public System.Nullable<int> Einheit
	{
		get
		{
			return this._Einheit;
		}
		set
		{
			if ((this._Einheit != value))
			{
				this.OnEinheitChanging(value);
				this.SendPropertyChanging();
				this._Einheit = value;
				this.SendPropertyChanged("Einheit");
				this.OnEinheitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preis", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Preis
	{
		get
		{
			return this._Preis;
		}
		set
		{
			if ((this._Preis != value))
			{
				this.OnPreisChanging(value);
				this.SendPropertyChanging();
				this._Preis = value;
				this.SendPropertyChanged("Preis");
				this.OnPreisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Steuer", DbType="VarChar(50)")]
	public string Steuer
	{
		get
		{
			return this._Steuer;
		}
		set
		{
			if ((this._Steuer != value))
			{
				this.OnSteuerChanging(value);
				this.SendPropertyChanging();
				this._Steuer = value;
				this.SendPropertyChanged("Steuer");
				this.OnSteuerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Betrag", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Betrag
	{
		get
		{
			return this._Betrag;
		}
		set
		{
			if ((this._Betrag != value))
			{
				this.OnBetragChanging(value);
				this.SendPropertyChanging();
				this._Betrag = value;
				this.SendPropertyChanged("Betrag");
				this.OnBetragChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterId", DbType="Int")]
	public System.Nullable<int> MasterId
	{
		get
		{
			return this._MasterId;
		}
		set
		{
			if ((this._MasterId != value))
			{
				if (this._Master_Credit.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMasterIdChanging(value);
				this.SendPropertyChanging();
				this._MasterId = value;
				this.SendPropertyChanged("MasterId");
				this.OnMasterIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Master_Credit_Master_Credit_Grid3", Storage="_Master_Credit", ThisKey="MasterId", OtherKey="Id", IsForeignKey=true)]
	public Master_Credit Master_Credit
	{
		get
		{
			return this._Master_Credit.Entity;
		}
		set
		{
			Master_Credit previousValue = this._Master_Credit.Entity;
			if (((previousValue != value) 
						|| (this._Master_Credit.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Master_Credit.Entity = null;
					previousValue.Master_Credit_Grid3s.Remove(this);
				}
				this._Master_Credit.Entity = value;
				if ((value != null))
				{
					value.Master_Credit_Grid3s.Add(this);
					this._MasterId = value.Id;
				}
				else
				{
					this._MasterId = default(Nullable<int>);
				}
				this.SendPropertyChanged("Master_Credit");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Master_Credit_Grid1")]
public partial class Master_Credit_Grid1 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Beschreibung;
	
	private System.Nullable<int> _Lange;
	
	private string _Züchter;
	
	private string _VP;
	
	private System.Nullable<int> _Menge;
	
	private System.Nullable<int> _Einheit;
	
	private System.Nullable<decimal> _Preis;
	
	private string _Steuer;
	
	private System.Nullable<decimal> _Betrag;
	
	private System.Nullable<int> _MasterId;
	
	private EntityRef<Master_Credit> _Master_Credit;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBeschreibungChanging(string value);
    partial void OnBeschreibungChanged();
    partial void OnLangeChanging(System.Nullable<int> value);
    partial void OnLangeChanged();
    partial void OnZüchterChanging(string value);
    partial void OnZüchterChanged();
    partial void OnVPChanging(string value);
    partial void OnVPChanged();
    partial void OnMengeChanging(System.Nullable<int> value);
    partial void OnMengeChanged();
    partial void OnEinheitChanging(System.Nullable<int> value);
    partial void OnEinheitChanged();
    partial void OnPreisChanging(System.Nullable<decimal> value);
    partial void OnPreisChanged();
    partial void OnSteuerChanging(string value);
    partial void OnSteuerChanged();
    partial void OnBetragChanging(System.Nullable<decimal> value);
    partial void OnBetragChanged();
    partial void OnMasterIdChanging(System.Nullable<int> value);
    partial void OnMasterIdChanged();
    #endregion
	
	public Master_Credit_Grid1()
	{
		this._Master_Credit = default(EntityRef<Master_Credit>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beschreibung", DbType="VarChar(50)")]
	public string Beschreibung
	{
		get
		{
			return this._Beschreibung;
		}
		set
		{
			if ((this._Beschreibung != value))
			{
				this.OnBeschreibungChanging(value);
				this.SendPropertyChanging();
				this._Beschreibung = value;
				this.SendPropertyChanged("Beschreibung");
				this.OnBeschreibungChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lange", DbType="Int")]
	public System.Nullable<int> Lange
	{
		get
		{
			return this._Lange;
		}
		set
		{
			if ((this._Lange != value))
			{
				this.OnLangeChanging(value);
				this.SendPropertyChanging();
				this._Lange = value;
				this.SendPropertyChanged("Lange");
				this.OnLangeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Züchter", DbType="VarChar(50)")]
	public string Züchter
	{
		get
		{
			return this._Züchter;
		}
		set
		{
			if ((this._Züchter != value))
			{
				this.OnZüchterChanging(value);
				this.SendPropertyChanging();
				this._Züchter = value;
				this.SendPropertyChanged("Züchter");
				this.OnZüchterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VP", DbType="VarChar(50)")]
	public string VP
	{
		get
		{
			return this._VP;
		}
		set
		{
			if ((this._VP != value))
			{
				this.OnVPChanging(value);
				this.SendPropertyChanging();
				this._VP = value;
				this.SendPropertyChanged("VP");
				this.OnVPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Menge", DbType="Int")]
	public System.Nullable<int> Menge
	{
		get
		{
			return this._Menge;
		}
		set
		{
			if ((this._Menge != value))
			{
				this.OnMengeChanging(value);
				this.SendPropertyChanging();
				this._Menge = value;
				this.SendPropertyChanged("Menge");
				this.OnMengeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Einheit", DbType="Int")]
	public System.Nullable<int> Einheit
	{
		get
		{
			return this._Einheit;
		}
		set
		{
			if ((this._Einheit != value))
			{
				this.OnEinheitChanging(value);
				this.SendPropertyChanging();
				this._Einheit = value;
				this.SendPropertyChanged("Einheit");
				this.OnEinheitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preis", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Preis
	{
		get
		{
			return this._Preis;
		}
		set
		{
			if ((this._Preis != value))
			{
				this.OnPreisChanging(value);
				this.SendPropertyChanging();
				this._Preis = value;
				this.SendPropertyChanged("Preis");
				this.OnPreisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Steuer", DbType="VarChar(50)")]
	public string Steuer
	{
		get
		{
			return this._Steuer;
		}
		set
		{
			if ((this._Steuer != value))
			{
				this.OnSteuerChanging(value);
				this.SendPropertyChanging();
				this._Steuer = value;
				this.SendPropertyChanged("Steuer");
				this.OnSteuerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Betrag", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Betrag
	{
		get
		{
			return this._Betrag;
		}
		set
		{
			if ((this._Betrag != value))
			{
				this.OnBetragChanging(value);
				this.SendPropertyChanging();
				this._Betrag = value;
				this.SendPropertyChanged("Betrag");
				this.OnBetragChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterId", DbType="Int")]
	public System.Nullable<int> MasterId
	{
		get
		{
			return this._MasterId;
		}
		set
		{
			if ((this._MasterId != value))
			{
				if (this._Master_Credit.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMasterIdChanging(value);
				this.SendPropertyChanging();
				this._MasterId = value;
				this.SendPropertyChanged("MasterId");
				this.OnMasterIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Master_Credit_Master_Credit_Grid1", Storage="_Master_Credit", ThisKey="MasterId", OtherKey="Id", IsForeignKey=true)]
	public Master_Credit Master_Credit
	{
		get
		{
			return this._Master_Credit.Entity;
		}
		set
		{
			Master_Credit previousValue = this._Master_Credit.Entity;
			if (((previousValue != value) 
						|| (this._Master_Credit.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Master_Credit.Entity = null;
					previousValue.Master_Credit_Grid1s.Remove(this);
				}
				this._Master_Credit.Entity = value;
				if ((value != null))
				{
					value.Master_Credit_Grid1s.Add(this);
					this._MasterId = value.Id;
				}
				else
				{
					this._MasterId = default(Nullable<int>);
				}
				this.SendPropertyChanged("Master_Credit");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Master_Credit_Grid2")]
public partial class Master_Credit_Grid2 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Beschreibung;
	
	private System.Nullable<int> _Lange;
	
	private string _Züchter;
	
	private string _VP;
	
	private System.Nullable<int> _Menge;
	
	private System.Nullable<int> _Einheit;
	
	private System.Nullable<decimal> _Preis;
	
	private string _Steuer;
	
	private System.Nullable<decimal> _Betrag;
	
	private System.Nullable<int> _MasterId;
	
	private EntityRef<Master_Credit> _Master_Credit;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBeschreibungChanging(string value);
    partial void OnBeschreibungChanged();
    partial void OnLangeChanging(System.Nullable<int> value);
    partial void OnLangeChanged();
    partial void OnZüchterChanging(string value);
    partial void OnZüchterChanged();
    partial void OnVPChanging(string value);
    partial void OnVPChanged();
    partial void OnMengeChanging(System.Nullable<int> value);
    partial void OnMengeChanged();
    partial void OnEinheitChanging(System.Nullable<int> value);
    partial void OnEinheitChanged();
    partial void OnPreisChanging(System.Nullable<decimal> value);
    partial void OnPreisChanged();
    partial void OnSteuerChanging(string value);
    partial void OnSteuerChanged();
    partial void OnBetragChanging(System.Nullable<decimal> value);
    partial void OnBetragChanged();
    partial void OnMasterIdChanging(System.Nullable<int> value);
    partial void OnMasterIdChanged();
    #endregion
	
	public Master_Credit_Grid2()
	{
		this._Master_Credit = default(EntityRef<Master_Credit>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beschreibung", DbType="VarChar(50)")]
	public string Beschreibung
	{
		get
		{
			return this._Beschreibung;
		}
		set
		{
			if ((this._Beschreibung != value))
			{
				this.OnBeschreibungChanging(value);
				this.SendPropertyChanging();
				this._Beschreibung = value;
				this.SendPropertyChanged("Beschreibung");
				this.OnBeschreibungChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lange", DbType="Int")]
	public System.Nullable<int> Lange
	{
		get
		{
			return this._Lange;
		}
		set
		{
			if ((this._Lange != value))
			{
				this.OnLangeChanging(value);
				this.SendPropertyChanging();
				this._Lange = value;
				this.SendPropertyChanged("Lange");
				this.OnLangeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Züchter", DbType="VarChar(50)")]
	public string Züchter
	{
		get
		{
			return this._Züchter;
		}
		set
		{
			if ((this._Züchter != value))
			{
				this.OnZüchterChanging(value);
				this.SendPropertyChanging();
				this._Züchter = value;
				this.SendPropertyChanged("Züchter");
				this.OnZüchterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VP", DbType="VarChar(50)")]
	public string VP
	{
		get
		{
			return this._VP;
		}
		set
		{
			if ((this._VP != value))
			{
				this.OnVPChanging(value);
				this.SendPropertyChanging();
				this._VP = value;
				this.SendPropertyChanged("VP");
				this.OnVPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Menge", DbType="Int")]
	public System.Nullable<int> Menge
	{
		get
		{
			return this._Menge;
		}
		set
		{
			if ((this._Menge != value))
			{
				this.OnMengeChanging(value);
				this.SendPropertyChanging();
				this._Menge = value;
				this.SendPropertyChanged("Menge");
				this.OnMengeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Einheit", DbType="Int")]
	public System.Nullable<int> Einheit
	{
		get
		{
			return this._Einheit;
		}
		set
		{
			if ((this._Einheit != value))
			{
				this.OnEinheitChanging(value);
				this.SendPropertyChanging();
				this._Einheit = value;
				this.SendPropertyChanged("Einheit");
				this.OnEinheitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preis", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Preis
	{
		get
		{
			return this._Preis;
		}
		set
		{
			if ((this._Preis != value))
			{
				this.OnPreisChanging(value);
				this.SendPropertyChanging();
				this._Preis = value;
				this.SendPropertyChanged("Preis");
				this.OnPreisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Steuer", DbType="VarChar(50)")]
	public string Steuer
	{
		get
		{
			return this._Steuer;
		}
		set
		{
			if ((this._Steuer != value))
			{
				this.OnSteuerChanging(value);
				this.SendPropertyChanging();
				this._Steuer = value;
				this.SendPropertyChanged("Steuer");
				this.OnSteuerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Betrag", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Betrag
	{
		get
		{
			return this._Betrag;
		}
		set
		{
			if ((this._Betrag != value))
			{
				this.OnBetragChanging(value);
				this.SendPropertyChanging();
				this._Betrag = value;
				this.SendPropertyChanged("Betrag");
				this.OnBetragChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterId", DbType="Int")]
	public System.Nullable<int> MasterId
	{
		get
		{
			return this._MasterId;
		}
		set
		{
			if ((this._MasterId != value))
			{
				if (this._Master_Credit.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnMasterIdChanging(value);
				this.SendPropertyChanging();
				this._MasterId = value;
				this.SendPropertyChanged("MasterId");
				this.OnMasterIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Master_Credit_Master_Credit_Grid2", Storage="_Master_Credit", ThisKey="MasterId", OtherKey="Id", IsForeignKey=true)]
	public Master_Credit Master_Credit
	{
		get
		{
			return this._Master_Credit.Entity;
		}
		set
		{
			Master_Credit previousValue = this._Master_Credit.Entity;
			if (((previousValue != value) 
						|| (this._Master_Credit.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Master_Credit.Entity = null;
					previousValue.Master_Credit_Grid2s.Remove(this);
				}
				this._Master_Credit.Entity = value;
				if ((value != null))
				{
					value.Master_Credit_Grid2s.Add(this);
					this._MasterId = value.Id;
				}
				else
				{
					this._MasterId = default(Nullable<int>);
				}
				this.SendPropertyChanged("Master_Credit");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
